forkbomb/urls.py
# -*- coding: utf-8 -*-

"""forkbomb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from sito.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index),
    url(r'azienda/register/$', AziendaCreate.as_view(), name='azienda-create'),
    url(r'azienda/update/(?P<pk>[0-9]+)/$', AziendaUpdate.as_view(), name='azienda-update'),
    url(r'azienda/profile/(?P<pk>[0-9]+)/$', AziendaDetailView.as_view(), name='azienda'),
    url(r'underconstruction/?$', underconstruction, name='underconstruction'),
    url(r'livemap/?$', livemap, name="livemap" ),
    url(r'catalogo-prodotti/?$', prodotti, name="catalogo-prodotti" ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sito/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver

from geopy.geocoders import Nominatim


class Azienda(models.Model):

    class Meta(object):
        verbose_name = "Azienda"
        verbose_name_plural = "Aziende"
    
    ragione_sociale = models.CharField(max_length=64, unique=True)
    utente = models.OneToOneField(User)
    indirizzo = models.CharField(max_length=256)
    citta = models.CharField(max_length=256)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lon = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    logo = models.ImageField(upload_to='uploads/aziende/', blank=True, null=True)
    telefono = models.CharField(max_length=64, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    sito = models.URLField(blank=True, null=True)
    url_facebook = models.URLField(blank=True, null=True)
    partita_iva = models.CharField(max_length=64)
    data_creazione = models.DateTimeField(auto_now_add=True)
    ultima_modifica = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('azienda', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.ragione_sociale

class Caratteristica(models.Model):

    class Meta(object):
        verbose_name = "Caratteristica"
        verbose_name_plural = "Caratteristiche"

    nome = models.CharField(max_length=128, unique=True)
    data_creazione = models.DateTimeField(auto_now_add=True)
    ultima_modifica = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.nome


class Tipologia(models.Model):

    class Meta(object):
        verbose_name = "Tipologia"
        verbose_name_plural = "Tipologie"

    nome = models.CharField(max_length=128, unique=True)
    descrizione = models.TextField()
    immagine = models.ImageField(upload_to='uploads/tipologie/', blank=True, null=True)
    data_creazione = models.DateTimeField(auto_now_add=True)
    ultima_modifica = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.nome


class Prodotto(models.Model):

    class Meta(object):
        verbose_name = "Prodotto"
        verbose_name_plural = "Prodotti"
    
    nome = models.CharField(max_length=64, unique=True)
    azienda = models.ForeignKey(Azienda)
    tipologia = models.ForeignKey(Tipologia)
    ingombro = models.CharField(max_length=64, verbose_name=u"Dimensione", null=True, blank=True)
    efficienza = models.IntegerField(help_text=u'percentuale', blank=True, null=True)
    potenza = models.IntegerField(help_text=u'in Watt')
    costo = models.DecimalField(max_digits=9, decimal_places=2, help_text=u'in Euro €', null=True, blank=True)
    ciclo_vita = models.IntegerField(help_text=u'Durata di vita del prodotto in mesi', null=True, blank=True) # mesi
    immagine = models.ImageField(upload_to='uploads/prodotti/', blank=True, null=True)
    caratteristiche = models.ManyToManyField(Caratteristica)
    data_creazione = models.DateTimeField(auto_now_add=True)
    ultima_modifica = models.DateTimeField(auto_now=True)

    def ritorno_investimento(self):
        pass

    def __unicode__(self):
        return self.nome


class Cliente(models.Model):

    class Meta(object):
        verbose_name = "Cliente"
        verbose_name_plural = "Clienti"
    
    ragione_sociale = models.CharField(max_length=64, blank=True, null=True)
    tipo = models.CharField(max_length=64, choices=(('PRIVATO', 'Privato'), ('AZIENDA', 'Azienda')))
    codice_fiscale = models.CharField(max_length=64, help_text=u'Se è un privato')
    partita_iva = models.CharField(max_length=64, help_text=u'Se è una azienda')
    utente = models.OneToOneField(User)
    indirizzo = models.CharField(max_length=256)
    citta = models.CharField(max_length=256)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lon = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    fabbisogno_energetico = models.IntegerField(help_text=u'KWh per mq per anno')
    data_creazione = models.DateTimeField(auto_now_add=True)
    ultima_modifica = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        if self.ragione_sociale:
            return self.ragione_sociale
        else:
            return self.utente.first_name + ' ' + self.utente.last_name


class Impianto(models.Model):

    class Meta(object):
        verbose_name = "Impianto"
        verbose_name_plural = "Impianti"
    
    cliente = models.ForeignKey(Cliente, null=True, blank=True)
    prodotto = models.ForeignKey(Prodotto)
    indirizzo = models.CharField(max_length=256, null=True, blank=True)
    citta = models.CharField(max_length=256)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lon = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    nome_installazione = models.CharField(max_length=256, blank=True, null=True, help_text=u"Eventuale nome dell'impianto installato")
    data_installazione = models.DateField(blank=True, null=True)
    resa_specifica = models.CharField(max_length=256, help_text=u'KWp (KW picco)')
    immagine = models.ImageField(upload_to='uploads/impianti/', blank=True, null=True)
    pubblicato = models.BooleanField(default=True)
    data_creazione = models.DateTimeField(auto_now_add=True)
    ultima_modifica = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        if self.nome_installazione:
            return self.nome_installazione
        else:
            return self.prodotto.nome +  ' - ' + self.citta



@receiver(pre_save, sender=Azienda)
@receiver(pre_save, sender=Cliente)
@receiver(pre_save, sender=Impianto)
def geolocate(sender, instance, *args, **kwargs):
    
    if not instance.lat and not instance.lon:

        geolocator = Nominatim(format_string='%s, Italy', view_box=('6', '48', '19', '36'), country_bias='it')
        address = instance.citta
        #if instance.indirizzo:
        #    address = instance.indirizzo + ', ' + address
        coords = geolocator.geocode(address)
        if coords:
            instance.lat = coords.latitude
            instance.lon = coords.longitude

sito/forms.py
# -*- coding: utf-8 -*-

from django import forms

from sito.models import *

from django.contrib.auth.models import User

class AziendaForm(forms.ModelForm):

    class Meta:

        model = Azienda
        fields = [
            'ragione_sociale', 
            'email', 
            'password',
            'password2',
            'indirizzo', 
            'citta', 
            'logo', 
            'telefono', 
            'sito', 
            'url_facebook', 
            'partita_iva', 
        ]

    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput(), label="Ripeti la password")

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists() or Azienda.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Questa email è già registrata"
            )
        return email

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")

        if password != password2:
            print password, password2
            raise forms.ValidationError(
                "Le password non corrispondono"
            )
        return password

sito/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from sito.models import *
from sito.forms import *

import simplejson as json

def index(request):

    tipologie = Tipologia.objects.all()
    prodotti = Prodotto.objects.all()
    impianti_count = Impianto.objects.count()

    return render(request, 'index.html', {
        'tipologie': tipologie,
        'prodotti': prodotti,
        'impianti_count': impianti_count,
    })

class AziendaCreate(CreateView):
    model = Azienda
    form_class = AziendaForm

    def form_valid(self, form):
        print form.cleaned_data
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = User.objects.create_user(username=email, email=email, password=password)
        form.instance.utente = user
        return super(AziendaCreate, self).form_valid(form)

class AziendaUpdate(UpdateView):
    form_class = AziendaForm
    model = Azienda
    success_url = reverse_lazy('azienda')

class AziendaDetailView(DetailView):
    model = Azienda

def livemap(request):

    impianti = Impianto.objects.filter(pubblicato=True, lat__isnull=False, lon__isnull=False)
    impianti_json = json.dumps(
        list(impianti.values('id', 'cliente', 'prodotto__nome', 'indirizzo', 'citta', 'lat', 'lon', 'resa_specifica', 'immagine', 'prodotto__tipologia__nome'))
    )
    tipologie = Tipologia.objects.all()

    potenza_totale = 0
    for i in impianti:
        potenza_totale += float(i.resa_specifica)
    potenza_totale = int(potenza_totale)
    potenza_totale = "{:,}".format(potenza_totale)

    return render(request, 'livemap.html', {
        'impianti': impianti,
        'impianti_json': impianti_json,
        'tipologie': tipologie,
        'potenza_totale': potenza_totale,
    })

def underconstruction(request):
    return render(request, 'login.html', {})

def prodotti(request):

    aziende = Azienda.objects.all()
    tipologie = Tipologia.objects.all()

    return render(request, 'prodotti.html', {
        'aziende': aziende,
        'tipologie': tipologie,
    })    

sito/templates/livemap.html
{% extends "base.html" %}

{% block content %}

<style>
#map {
    height: 500px;
}

#livemap {
    margin-top: 150px;
}

#potenza h2 {
    font-size: 35px;
}

#potenza p {
    font-size: 30px;
}

.leaflet-popup-content p {
    margin: 2px 0;
}
</style>

<section id="livemap">
    <div class="container">
        <div class="row">
            <div id="potenza">
                <h2>Potenza totale generata</h2>
                <p>{{ potenza_totale }} KWp</p>
            </div>
            <div id="map"></div>
        </div>          
    </div>  
</section>

{% endblock %}

{% block bottom_script %}
<script>

    var tipologie = {};
    var LeafIcon = L.Icon.extend({
        options: {
            iconSize: [20, 20]
        }
    });
    {% for t in tipologie %}
    tipologie['{{t.nome}}'] = new LeafIcon({iconUrl: '{{t.immagine.url}}'});
    {% endfor %}
    window.impianti = {{impianti_json|safe}};

    window.map = L.map('map').setView([43.33316939281735, 13.364868164062502], 6);
    L.tileLayer(
        'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 
        {
            maxZoom: 19
        }
    ).addTo(map);

    $.each(impianti, function(i, e){
        var marker = L.marker(
            [e.lat, e.lon], 
            {
                icon: tipologie[e.prodotto__tipologia__nome]
            }
        );
        var popup_content = '<b>'+e.prodotto__nome+'</b><p>'+e.prodotto__tipologia__nome+'</p><p>'+e.resa_specifica+' KWp</p>';
        if(e.immagine != "") {
            popup_content += '<img style="width:200px;" src="/files/'+e.immagine+'">';
        }
        marker.bindPopup(popup_content);
        marker.addTo(map);
    });
</script>


{% endblock %}

sito/templates/login.html
{% extends "base.html" %} 

{% block content %}
<section id="login" style="height: 450px;
background-color: #ffffff;
background-image: url(static/sito/img/login.jpg);
background-repeat: no-repeat;
background-size: cover;
background-position: bottom center;
background-attachment: fixed;">

    <div class="container">                                                                                                                       
        <div class="wrap_caption">
            <div class="caption_carousel">
                <p>Pagina in construzione</p>
            </div>
        </div>
    </div>

</section>
{% endblock %}

sito/templates/prodotti.html
{% extends "base.html" %}

{% block content %}

<style>

#crea-impianto {
    margin-top: 150px;
}

.prodotto {
    width: auto;
    float: left;
    margin-right: 30px;
    padding: 20px;
    border-radius: 5px;
    margin-top: 20px;
}

.prodotto:hover {
    background-color: #d9d9ff;
}

.selezionato {
    background-color: #6c6cff;
}

.azienda-nome {
    font-size: 35px;
}

.azienda {
    background-color: #d0d0d0;
    border-radius: 5px;
    padding: 20px;
}

#titolo h1 {
    font-size: 45px;
}
#titolo h2 {
    font-size: 35px;
}

#risultato {
    margin-top: 30px;
}

#risultato p {
    font-size: 35px;
}

</style>

<section id="crea-impianto">
    <div class="container">
        <div class="row" id="titolo"> 
            <h1>In questa pagina puoi sfogliare il catalogo di tutte le aziende</h1>
            <h2>Seleziona i prodotti per configurare e simulare il tuo impianto</h2>
        </div>
        <div id="prodotti">
            {% for azienda in aziende %}
            <div class="row" style="margin-top: 50px;">
                <div class="azienda">
                    {% if azienda.logo %}
                        <p><img style="height: 50px;" src="{{ azienda.logo.url }}"></p>
                    {% endif %}
                    <h1 class="azienda-nome">{{ azienda.ragione_sociale }}</h1>
                    <p>{% if azienda.indirizzo %}{{ azienda.indirizzo }}{% endif %} - {{azienda.citta}}</p>
                    <p><a href="{{azienda.sito}}">{{azienda.sito}}</a></p>
                </div>
                {% for p in azienda.prodotto_set.all %}
                    <div class="prodotto" data-resa="{{ p.potenza }}">
                        <h2>{{ p.nome }}</h2>
                        <i>{{ p.tipologia.nome }}</i>
                        {% if p.immagine %}
                            <p><img style="width: 150px; max-height: 400px;" src="{{ p.immagine.url }}"></p>
                        {% endif %}
                        {% if p.ingombro %}
                            <p><b>Ingombro</b>: <i>{{p.ingombro}}</i></p>
                        {% endif %}
                        {% if p.efficienza %}
                            <p><b>Efficienza</b>: <i>{{p.efficienza}}%</i></p>
                        {% endif %}
                        {% if p.potenza %}
                            <p><b>Potenza</b>: <i>{{p.potenza}} W</i></p>
                        {% endif %}
                        {% if p.costo %}
                            <p><b>Costo</b>: <i>{{p.costo}} €</i></p>
                        {% endif %}
                        {% if p.ciclo_vita %}
                            <p><b>Ciclo di vita</b>: <i>{{p.ciclo_vita}} mesi</i></p>
                        {% endif %}

                    </div>
                {% endfor %}
            </div>          
            {% endfor %}
        </div>
</section>

<hr>
<section id="">
    <div class="container">
        <div class="row">
            <h1>Crea il tuo impianto</h1>
        </div>
        <div class="row">
            <h2>Potenza rinnovabile selezionata:</h2>
            <div id="potenza-totale"></div>
        </div>          
        <div class="row">
            <h2>Indica la tua provincia</h2>
        </div>
        <div class="row">
            <select id="provincia">
                <option>Agrigento</option>
                <option>Alessandria</option>
                <option>Ancona</option>
                <option>Andria</option>
                <option>Aosta</option>
                <option>Arezzo</option>
                <option>Ascoli Piceno</option>
                <option>Asti</option>
                <option>Avellino</option>
                <option>Bari</option>
                <option>Barletta</option>
                <option>Belluno</option>
                <option>Benevento</option>
                <option>Bergamo</option>
                <option>Biella</option>
                <option>Bologna</option>
                <option>Bolzano</option>
                <option>Brescia</option>
                <option>Brindisi</option>
                <option>Cagliari</option>
                <option>Caltanissetta</option>
                <option>Campobasso</option>
                <option>Carbonia</option>
                <option>Caserta</option>
                <option>Catania</option>
                <option>Catanzaro</option>
                <option>Chieti</option>
                <option>Como</option>
                <option>Cosenza</option>
                <option>Cremona</option>
                <option>Crotone</option>
                <option>Cuneo</option>
                <option>Enna</option>
                <option>Fermo</option>
                <option>Ferrara</option>
                <option>Firenze</option>
                <option>Foggia</option>
                <option>Forlì</option>
                <option>Frosinone</option>
                <option>Genova</option>
                <option>Gorizia</option>
                <option>Grosseto</option>
                <option>Iglesias</option>
                <option>Imperia</option>
                <option>Isernia</option>
                <option>L'Aquila</option>
                <option>La Spezia</option>
                <option>Lanusei</option>
                <option>Latina</option>
                <option>Lecce</option>
                <option>Lecco</option>
                <option>Livorno</option>
                <option>Lodi</option>
                <option>Lucca</option>
                <option>Macerata</option>
                <option>Mantova</option>
                <option>Massa</option>
                <option>Matera</option>
                <option>Messina</option>
                <option>Milano</option>
                <option>Modena</option>
                <option>Monza</option>
                <option>Napoli</option>
                <option>Novara</option>
                <option>Nuoro</option>
                <option>Olbia</option>
                <option>Oristano</option>
                <option>Padova</option>
                <option>Palermo</option>
                <option>Parma</option>
                <option>Pavia</option>
                <option>Perugia</option>
                <option>Pesaro</option>
                <option>Pescara</option>
                <option>Piacenza</option>
                <option>Pisa</option>
                <option>Pistoia</option>
                <option>Pordenone</option>
                <option>Potenza</option>
                <option>Prato</option>
                <option>Ragusa</option>
                <option>Ravenna</option>
                <option>Reggio di Calabria</option>
                <option>Reggio nell'Emilia</option>
                <option>Rieti</option>
                <option>Rimini</option>
                <option>Roma</option>
                <option>Rovigo</option>
                <option>Salerno</option>
                <option>Sanluri</option>
                <option>Sassari</option>
                <option>Savona</option>
                <option>Siena</option>
                <option>Siracusa</option>
                <option>Sondrio</option>
                <option>Taranto</option>
                <option>Tempio Pausania</option>
                <option>Teramo</option>
                <option>Terni</option>
                <option>Torino</option>
                <option>Tortolì</option>
                <option>Trani</option>
                <option>Trapani</option>
                <option>Trento</option>
                <option>Treviso</option>
                <option>Trieste</option>
                <option>Udine</option>
                <option>Varese</option>
                <option>Venezia</option>
                <option>Verbania</option>
                <option>Vercelli</option>
                <option>Verona</option>
                <option>Vibo Valentia</option>
                <option>Vicenza</option>
                <option>Villacidro</option>
                <option>Viterbo</option>
            </select>
            <br>
            <br>
            <br>
            <div>Consumo annuale pro-capite:</div>
            <div id="consumo-annuo-provincia"></div>
        </div>
        <div class="row">
            <h2>Quante persone ci sono nella tua abitazione?</h2>
        </div>
        <div class="row">
            <input id="persone" type="number" min="1">
        </div>
        <div class="row" style="margin-top: 30px;">
            <button class="btn" id="calcola">CALCOLA</button>
        </div>
        <div id="risultato">
        </div>
    </div>  
</section>


{% endblock %}

{% block bottom_script %}
<script>

window.potenza_totale = 0

$('.prodotto').on('click', function(){
    var prodotto = $(this);
    var potenza = prodotto.data('resa');
    if(prodotto.hasClass('selezionato')) {
        prodotto.removeClass('selezionato');
        potenza_totale -= potenza;
    } else {
        prodotto.addClass('selezionato');
        potenza_totale += potenza;
    }
    $('#potenza-totale').text(potenza_totale + ' KWp');

});

$('#provincia').on('change', function(){
    var provincia = $('#provincia').find(":selected").text();
    window.consumo_annuo_provincia = province[provincia];
    $('#consumo-annuo-provincia').text(window.consumo_annuo_provincia + ' TWp')
});

$('#calcola').on('click', function(){
    console.log(potenza_totale);
    var persone = $('#persone').val();
    var consumo_casa = (window.consumo_annuo_provincia * persone);
    var indipendenza = (potenza_totale * 0.1) / consumo_casa;
    $('#risultato').text('');
    $('#risultato').append('<p>Consumo annuale della casa: <br><b>'+consumo_casa+' TWp</b>');
    $('#risultato').append('<p>Indice di indipendenza energetica: <br><b>'+parseInt(indipendenza)+'%</b></p>');
});

province = {
"Torino": 1133.6889082,
"Vercelli": 994.17039408,
"Novara": 1128.8682241,
"Cuneo": 1067.4977961,
"Asti": 1091.0655079,
"Alessandria": 1095.0585435,
"Biella": 1222.0843323,
"Verbania": 1008.8397809,
"Aosta": 1345.7026269,
"Imperia": 1107.6501265,
"Savona": 1063.7702455,
"Genova": 1092.6037295,
"La Spezia": 1038.665233,
"Varese": 1206.0406484,
"Como": 1147.0063159,
"Sondrio": 1131.33263,
"Milano": 1024.5924882,
"Bergamo": 1255.007813,
"Brescia": 1073.4756978,
"Pavia": 1269.1489013,
"Cremona": 1214.8434137,
"Mantova": 1294.2242193,
"Lecco": 1151.3394016,
"Lodi": 1130.8973048,
"Monza": 1201.3997778,
"Bolzano": 1291.1410935,
"Trento": 895.67797222,
"Verona": 1056.9911812,
"Vicenza": 1000.2866592,
"Belluno": 1054.4408975,
"Treviso": 1257.7690746,
"Venezia": 1179.9914193,
"Padova": 1277.1677152,
"Rovigo": 1129.538069,
"Udine": 1127.0489956,
"Gorizia": 971.54053528,
"Trieste": 1163.4766988,
"Pordenone": 1156.3950195,
"Piacenza": 1158.4418982,
"Parma": 1086.8107008,
"Reggio dell'Emilia": 1162.9093504,
"Modena": 1082.8799449,
"Bologna": 1263.2446081,
"Ferrara": 1270.5148076,
"Ravenna": 1264.399614,
"Forlì": 1105.49992,
"Rimini": 1151.2215877,
"Massa": 1082.2147544,
"Lucca": 1264.350028,
"Pistoia": 1177.9849125,
"Firenze": 1194.7694865,
"Livorno": 1080.1921824,
"Pisa": 1306.9142482,
"Arezzo": 1079.2028231,
"Siena": 1249.1916203,
"Grosseto": 1122.6954096,
"Prato": 1124.7992315,
"Perugia": 1125.8229454,
"Terni": 979.37260566,
"Pesaro": 1112.4755107,
"Ancona": 1013.0871562,
"Macerata": 1056.1285043,
"Ascoli Piceno": 1031.932498,
"Fermo": 1048.7128211,
"Viterbo": 1124.3725173,
"Rieti": 1016.6931893,
"Roma": 1448.9412331,
"Latina": 1220.7320383,
"Frosinone": 1054.1443074,
"L'Aquila": 1026.2849714,
"Teramo": 1035.241501,
"Pescara": 1113.5970104,
"Chieti": 1044.5867139,
"Campobasso": 908.64494183,
"Isernia": 954.27931548,
"Caserta": 1116.6187701,
"Benevento": 982.07016339,
"Napoli": 1068.2794576,
"Avellino": 953.29022729,
"Salerno": 999.41222318,
"Foggia": 969.12130458,
"Bari": 1226.2249342,
"Taranto": 1205.1894875,
"Brindisi": 1049.7083861,
"Lecce": 1223.6340957,
"Andria": 941.13643845,
"Barletta": 957.33227434,
"Trani": 909.34694697,
"Potenza": 928.97109818,
"Matera": 953.61119469,
"Cosenza": 994.26221684,
"Catanzaro": 1078.2062494,
"Reggio di Calabria": 1291.4288274,
"Crotone": 1060.8744254,
"Vibo Valentia": 1034.4463478,
"Trapani": 1283.8031608,
"Palermo": 1256.7105098,
"Messina": 1166.4890564,
"Agrigento": 1269.6068996,
"Caltanissetta": 1129.3389123,
"Enna": 1087.9101095,
"Catania": 1315.0504446,
"Ragusa": 1154.8088709,
"Siracusa": 1242.9969468,
"Sassari": 1345.2108326,
"Nuoro": 1210.6275881,
"Cagliari": 1593.1142863,
"Oristano": 1315.5353996,
"Olbia": 1604.0686999,
"Tempio Pausania": 1232.8727146,
"Lanusei": 1015.7356058,
"Tortolì": 1168.0962869,
"Sanluri": 1224.6825191,
"Villacidro": 1026.1938479,
"Carbonia": 1383.7085449,
"Iglesias": 1285.4240974,
}


</script>


{% endblock %}